from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlparse

from .projects import resolve_project_id


@dataclass(frozen=True)
class ConstraintHint:
    field: str
    operator: str
    value: Any
    source: str


@dataclass(frozen=True)
class DeterministicTaskObjective:
    web_project_id: str
    use_case: str
    seed: int
    task_url: str
    prompt: str
    route_target: str
    field_values: dict[str, str]
    entity_filters: dict[str, Any]
    auth_required: bool
    success_expectations: dict[str, Any]
    constraints: tuple[ConstraintHint, ...]
    relevant_data: dict[str, Any]
    raw_task: dict[str, Any]


_FIELD_ALIASES: dict[str, str] = {
    "author": "name",
    "bio": "bio",
    "cast": "cast",
    "comment_content": "content",
    "comment_name": "name",
    "confirm_password": "confirm_password",
    "content": "content",
    "director": "director",
    "duration": "duration",
    "email": "email",
    "favorite_genres": "favorite_genres",
    "first_name": "first_name",
    "genre_name": "genres",
    "genres": "genres",
    "location": "location",
    "message": "message",
    "movie_name": "movie_name",
    "name": "name",
    "password": "password",
    "query": "query",
    "rating": "rating",
    "subject": "subject",
    "synopsis": "synopsis",
    "title": "title",
    "trailer_url": "trailer_url",
    "url": "website",
    "user": "username",
    "username": "username",
    "website": "website",
    "year": "year",
}

_ROUTE_BY_USE_CASE: dict[str, str] = {
    "ADD_COMMENT": "/movies",
    "ADD_FILM": "/profile",
    "ADD_TO_WATCHLIST": "/movies",
    "CONTACT": "/contact",
    "DELETE_FILM": "/profile",
    "EDIT_FILM": "/profile",
    "EDIT_USER": "/profile",
    "FILM_DETAIL": "/movies",
    "FILTER_FILM": "/search",
    "LOGIN": "/login",
    "LOGOUT": "/profile",
    "REGISTRATION": "/register",
    "REMOVE_FROM_WATCHLIST": "/movies",
    "SEARCH_FILM": "/search",
    "SHARE_MOVIE": "/movies",
    "WATCH_TRAILER": "/movies",
}

_DEFAULT_VALUES: dict[str, str] = {
    "bio": "films lover",
    "cast": "John,Roy",
    "confirm_password": "Passw0rd!",
    "content": "Great movie",
    "director": "Anthony Russo",
    "duration": "120",
    "email": "agent@example.com",
    "favorite_genres": "Drama, Action",
    "first_name": "Benjamin",
    "genres": "Action",
    "last_name": "Viewer",
    "location": "Madrid",
    "message": "Please help with my movie request.",
    "name": "Agent",
    "password": "Passw0rd!",
    "query": "The Matrix",
    "rating": "5.0",
    "subject": "General inquiry",
    "synopsis": "A thrilling movie generated by the deterministic harvester.",
    "title": "New Film",
    "trailer_url": "https://example.org/trailer",
    "username": "user1",
    "website": "https://example.org",
    "year": "2021",
}

_MOVIE_FILTER_FIELDS = {
    "movie_name",
    "title",
    "director",
    "genres",
    "year",
    "duration",
    "rating",
}


def _norm_ws(text: str) -> str:
    return " ".join(str(text or "").split())


def _prompt_constraints(task: str) -> dict[str, str]:
    text = str(task or "")
    out: dict[str, str] = {}
    pattern = re.compile(
        r"\b([a-z][a-z0-9 _-]{1,40})\b\s*(?:equals|=|is|:)\s*(?:'([^']+)'|\"([^\"]+)\"|(<[^>]+>)|([0-9]+(?:\.[0-9]+)?)|([^\s,;]+))",
        flags=re.I,
    )
    for match in pattern.finditer(text):
        raw_key = _norm_ws(match.group(1) or "").lower()
        key = re.sub(r"^(?:the|a|an)\s+", "", raw_key).strip().replace(" ", "_")
        value = next((group for group in match.groups()[1:] if group), "")
        value = _norm_ws(value).strip(" \t\r\n'\"`.,;:!?")
        if not key or not value:
            continue
        out[key[:40]] = value[:120]
        if len(out) >= 16:
            break
    return out


def _normalize_field(raw: str) -> str:
    key = str(raw or "").strip().lower().replace(" ", "_").replace(".", "_")
    while "__" in key:
        key = key.replace("__", "_")
    return _FIELD_ALIASES.get(key, key)


def extract_seed_from_task_url(task_url: str) -> int:
    try:
        parsed = urlparse(str(task_url))
        query = parse_qs(parsed.query or "")
        values = query.get("seed") or []
        if values:
            return max(1, min(int(values[0]), 999))
    except Exception:
        return 1
    return 1


def _extract_seed(task_url: str) -> int:
    return extract_seed_from_task_url(task_url)


def _load_raw_task_rows(cache_path: Path) -> list[dict[str, Any]]:
    payload = json.loads(cache_path.read_text(encoding="utf-8"))
    rows: Any
    if isinstance(payload, dict) and isinstance(payload.get("tasks"), list):
        rows = payload["tasks"]
    elif isinstance(payload, dict):
        nested_rows: list[dict[str, Any]] = []
        for value in payload.values():
            if isinstance(value, dict) and isinstance(value.get("tasks"), list):
                nested_rows.extend(row for row in value["tasks"] if isinstance(row, dict))
        rows = nested_rows if nested_rows else payload
    else:
        rows = payload
    return [row for row in rows if isinstance(row, dict)] if isinstance(rows, list) else []


def load_task_rows(*, cache_path: Path, use_case: str, web_project_id: str | None = None) -> list[dict[str, Any]]:
    normalized = str(use_case or "").strip().upper()
    normalized_project = str(web_project_id or "").strip()
    matched: list[dict[str, Any]] = []
    for row in _load_raw_task_rows(cache_path):
        row_project = str(row.get("web_project_id") or "").strip()
        if normalized_project and row_project and row_project != normalized_project:
            continue
        use_case_payload = row.get("use_case")
        name = str(use_case_payload.get("name") or "") if isinstance(use_case_payload, dict) else ""
        if name.strip().upper() == normalized:
            matched.append(row)
    return matched


def load_task_row(*, cache_path: Path, use_case: str, seed: int | None = None, web_project_id: str | None = None) -> dict[str, Any]:
    matched = load_task_rows(cache_path=cache_path, use_case=use_case, web_project_id=web_project_id)
    if not matched:
        raise ValueError(f"No task found for use_case={use_case} in {cache_path}")
    if seed is None:
        return matched[0]
    target_seed = int(seed)
    for row in matched:
        if extract_seed_from_task_url(str(row.get("url") or "")) == target_seed:
            return row
    return matched[0]


def task_seeds_for_use_case(*, cache_path: Path, use_case: str, web_project_id: str | None = None) -> list[int]:
    seeds: list[int] = []
    seen: set[int] = set()
    for row in load_task_rows(cache_path=cache_path, use_case=use_case, web_project_id=web_project_id):
        seed = extract_seed_from_task_url(str(row.get("url") or ""))
        if seed in seen:
            continue
        seen.add(seed)
        seeds.append(seed)
    return seeds


def _flatten_criteria(prefix: str, payload: Any) -> list[tuple[str, Any]]:
    if isinstance(payload, dict) and "operator" in payload and "value" in payload:
        return [(prefix, payload)]
    if isinstance(payload, dict):
        flattened: list[tuple[str, Any]] = []
        for key, value in payload.items():
            next_prefix = f"{prefix}_{key}" if prefix else str(key)
            flattened.extend(_flatten_criteria(next_prefix, value))
        return flattened
    return [(prefix, payload)]


def _constraint_hints_from_task(task_row: dict[str, Any]) -> list[ConstraintHint]:
    hints: list[ConstraintHint] = []
    use_case_payload = task_row.get("use_case")
    if isinstance(use_case_payload, dict):
        for constraint in use_case_payload.get("constraints") or []:
            if not isinstance(constraint, dict):
                continue
            hints.append(
                ConstraintHint(
                    field=_normalize_field(str(constraint.get("field") or "")),
                    operator=str(constraint.get("operator") or "equals").strip().lower(),
                    value=constraint.get("value"),
                    source="use_case.constraints",
                )
            )
    for test in task_row.get("tests") or []:
        if not isinstance(test, dict) or str(test.get("type") or "") != "CheckEventTest":
            continue
        criteria = test.get("event_criteria")
        if not isinstance(criteria, dict):
            continue
        for field, value in _flatten_criteria("", criteria):
            normalized_field = _normalize_field(field)
            if isinstance(value, dict) and "operator" in value and "value" in value:
                hints.append(
                    ConstraintHint(
                        field=normalized_field,
                        operator=str(value.get("operator") or "equals").strip().lower(),
                        value=value.get("value"),
                        source="tests.event_criteria",
                    )
                )
            else:
                hints.append(
                    ConstraintHint(
                        field=normalized_field,
                        operator="equals",
                        value=value,
                        source="tests.event_criteria",
                    )
                )
    for field, value in _prompt_constraints(str(task_row.get("prompt") or "")).items():
        hints.append(
            ConstraintHint(
                field=_normalize_field(field),
                operator="equals",
                value=value,
                source="prompt",
            )
        )
    return hints


def _coerce_scalar(value: Any) -> str:
    if isinstance(value, list):
        return str(value[0]).strip() if value else ""
    return str(value).strip()


def _pick_value(field: str, operator: str, value: Any, seed: int) -> str:
    raw = _coerce_scalar(value)
    if operator in {"equals", "contains", "in_list"} and raw:
        return raw
    if field in {"rating", "year", "duration"} and raw:
        try:
            numeric = float(raw)
        except Exception:
            return raw
        if operator in {"greater_than", "greater_equal"}:
            return str(int(numeric) if numeric.is_integer() else numeric)
        if operator in {"less_than", "less_equal"}:
            adjusted = max(1.0, numeric - 1.0) if operator == "less_than" else numeric
            return str(int(adjusted) if adjusted.is_integer() else adjusted)
        return raw
    candidate = _DEFAULT_VALUES.get(field, f"Agent {seed}")
    if operator in {"not_equals", "not_contains", "not_in_list"} and raw:
        lowered = raw.lower()
        if lowered not in candidate.lower():
            return candidate
        return f"{candidate}-{seed}"
    return raw or candidate


def _maybe_store_field_value(field_values: dict[str, str], hint: ConstraintHint, seed: int) -> None:
    if not hint.field:
        return
    if hint.field in _MOVIE_FILTER_FIELDS and hint.field not in {"title", "director", "genres", "year", "duration", "rating"}:
        return
    if hint.field not in _DEFAULT_VALUES and hint.field not in {"title", "director", "genres", "year", "duration", "rating", "movie_name"}:
        return
    if hint.field in field_values and hint.operator not in {"equals", "contains"}:
        return
    chosen = _pick_value(hint.field, hint.operator, hint.value, seed)
    if chosen:
        field_values.setdefault(hint.field, chosen)
        if hint.operator in {"equals", "contains"}:
            field_values[hint.field] = chosen


def _update_entity_filters(filters: dict[str, Any], hint: ConstraintHint) -> None:
    raw = _coerce_scalar(hint.value)
    if not raw:
        return
    if hint.field in {"movie_name", "title"}:
        if hint.operator == "equals":
            filters["name_exact"] = raw
        elif hint.operator == "contains":
            filters["name_contains"] = raw
        elif hint.operator == "not_contains":
            filters["name_not_contains"] = raw
    elif hint.field == "director":
        if hint.operator == "equals":
            filters["director_exact"] = raw
        elif hint.operator == "contains":
            filters["director_contains"] = raw
    elif hint.field == "genres":
        if hint.operator == "equals":
            filters["genre_exact"] = raw
        elif hint.operator in {"contains", "not_contains"}:
            filters["genre_contains" if hint.operator == "contains" else "genre_not_contains"] = raw
    elif hint.field == "duration":
        if hint.operator in {"greater_than", "greater_equal"}:
            filters["duration_gte"] = int(float(raw))
        elif hint.operator in {"less_than", "less_equal"}:
            filters["duration_lte"] = int(float(raw))
    elif hint.field == "rating":
        if hint.operator in {"greater_than", "greater_equal"}:
            filters["rating_gte"] = float(raw)
        elif hint.operator in {"less_than", "less_equal"}:
            filters["rating_lte"] = float(raw)
    elif hint.field == "year":
        if hint.operator in {"greater_than", "greater_equal"}:
            filters["year_gte"] = int(float(raw))
        elif hint.operator in {"less_than", "less_equal"}:
            filters["year_lte"] = int(float(raw))


def _relevant_data_payload(task_row: dict[str, Any]) -> dict[str, Any]:
    payload = task_row.get("relevant_data")
    return dict(payload) if isinstance(payload, dict) else {}


def _auth_required(use_case: str, field_values: dict[str, str]) -> bool:
    public_cases = {
        "ADD_COMMENT",
        "CONTACT",
        "FILM_DETAIL",
        "FILTER_FILM",
        "LOGIN",
        "REGISTRATION",
        "SEARCH_FILM",
        "SHARE_MOVIE",
        "WATCH_TRAILER",
    }
    if use_case in public_cases:
        return use_case in {"LOGIN", "REGISTRATION"}
    protected_cases = {"ADD_FILM", "ADD_TO_WATCHLIST", "DELETE_FILM", "EDIT_FILM", "EDIT_USER", "LOGOUT", "REMOVE_FROM_WATCHLIST"}
    return bool(field_values.get("username") or field_values.get("password") or use_case in protected_cases)


def normalize_task_row(task_row: dict[str, Any], *, seed: int | None = None) -> DeterministicTaskObjective:
    use_case_payload = task_row.get("use_case")
    web_project_id = resolve_project_id(task_row)
    use_case = str((use_case_payload or {}).get("name") or "").strip().upper()
    task_url = str(task_row.get("url") or "")
    task_seed = int(seed or _extract_seed(task_url))
    field_values: dict[str, str] = {}
    entity_filters: dict[str, Any] = {}
    constraints = _constraint_hints_from_task(task_row)

    for hint in constraints:
        _maybe_store_field_value(field_values, hint, task_seed)
        _update_entity_filters(entity_filters, hint)

    relevant_data = _relevant_data_payload(task_row)
    login_user = relevant_data.get("user_for_login")
    if isinstance(login_user, dict):
        username = _coerce_scalar(login_user.get("username"))
        password = _coerce_scalar(login_user.get("password"))
        if username:
            field_values.setdefault("username", username)
        if password:
            field_values.setdefault("password", password)

    field_values.setdefault("username", _DEFAULT_VALUES["username"])
    field_values.setdefault("password", _DEFAULT_VALUES["password"])

    if "movie_name" in field_values and "query" not in field_values:
        field_values["query"] = field_values["movie_name"]
    if "name_exact" in entity_filters and "query" not in field_values:
        field_values["query"] = str(entity_filters["name_exact"])
    if "name_contains" in entity_filters and "query" not in field_values:
        field_values["query"] = str(entity_filters["name_contains"])

    success_expectations = {
        "event_names": [str(test.get("event_name") or "").strip() for test in (task_row.get("tests") or []) if isinstance(test, dict) and str(test.get("event_name") or "").strip()],
        "texts": [],
        "url_contains": [],
    }
    route_target = _ROUTE_BY_USE_CASE.get(use_case, "/")
    if use_case == "CONTACT":
        success_expectations["texts"] = ["Message Sent!"]
        success_expectations["url_contains"] = ["/contact"]
    elif use_case in {"LOGIN", "REGISTRATION", "EDIT_USER", "ADD_FILM", "EDIT_FILM", "DELETE_FILM", "LOGOUT"}:
        success_expectations["url_contains"] = ["/profile", "/"]
    elif use_case in {"ADD_TO_WATCHLIST", "REMOVE_FROM_WATCHLIST", "SHARE_MOVIE", "WATCH_TRAILER", "ADD_COMMENT", "FILM_DETAIL"}:
        success_expectations["url_contains"] = ["/movies/"]
    elif use_case in {"SEARCH_FILM", "FILTER_FILM"}:
        success_expectations["url_contains"] = ["/search"]

    return DeterministicTaskObjective(
        web_project_id=web_project_id,
        use_case=use_case,
        seed=task_seed,
        task_url=task_url,
        prompt=str(task_row.get("prompt") or ""),
        route_target=route_target,
        field_values=field_values,
        entity_filters=entity_filters,
        auth_required=_auth_required(use_case, field_values),
        success_expectations=success_expectations,
        constraints=tuple(constraints),
        relevant_data=relevant_data,
        raw_task=task_row,
    )


def load_task_objective(*, cache_path: Path, use_case: str, seed: int | None = None, web_project_id: str | None = None) -> DeterministicTaskObjective:
    row = load_task_row(cache_path=cache_path, use_case=use_case, seed=seed, web_project_id=web_project_id)
    if seed is None:
        return normalize_task_row(dict(row))
    row_seed = extract_seed_from_task_url(str(row.get("url") or ""))
    if row_seed == int(seed):
        return normalize_task_row(dict(row), seed=int(seed))
    normalized = dict(row)
    normalized["url"] = str(row.get("url") or "").split("?")[0] + f"?seed={int(seed)}"
    return normalize_task_row(normalized, seed=seed)


__all__ = [
    "ConstraintHint",
    "DeterministicTaskObjective",
    "extract_seed_from_task_url",
    "load_task_objective",
    "load_task_row",
    "load_task_rows",
    "normalize_task_row",
    "task_seeds_for_use_case",
]
